
export const AUTH_AUTHENTICATING = 'AUTH_AUTHENTICATING'
export const AUTH_AUTHENTICATED_SUCCESS = 'AUTH_AUTHENTICATED_SUCCESS'
export const AUTH_AUTHENTICATED_ERROR = 'AUTH_AUTHENTICATED_ERROR'
export const AUTH_GETTING_SESSION = 'AUTH_GETTING_SESSION'
export const AUTH_GETTING_SESSION_SUCCESS = 'AUTH_GETTING_SESSION_SUCCESS'
export const AUTH_GETTING_SESSION_ERROR = 'AUTH_GETTING_SESSION_ERROR'
