global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: '{{cookiecutter.project_name}}-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: "webserver"
    scrape_interval: "15s"
    target_groups:
    - targets: ['localhost:8001']
  - job_name: "node"
    scrape_interval: "15s"
    target_groups:
    - targets: ['localhost:9100']
  - job_name: "mongodb"
    scrape_interval: "15s"
    target_groups:
    - targets: ['localhost:9002']
